# trait used to check
### ./test_pdfs//Käfer_et_al_2014_Dioecy_is_associated_with_higher_diversification_r.txt
an angiosperm-wide analysis could detect such an effect. 1487 sister clade comparisons are (still) a useful tool these past years have seen the development of several methods for studying the evolution of traits and their effect on species diversification on the phylogeny. these were first limited to anagenetic binary traits (bisse – binary state speciation and extinction model, maddison et al., 2007; fitzjohn et al., 2009) and were rapidly extended to multistate traits (musse), quantitative traits (quasse, fitzjohn, 2010), incorporating cladogenetic transitions (classe, goldberg & igi\002c, 2012; and bisseness, magnuson-ford & otto, 2012) and other effects (see diversitree website, http://www.zoology.ubc.ca/ prog/diversitree/).

diversification on the phylogeny. these were first limited to anagenetic binary traits (bisse – binary state speciation and extinction model, maddison et al., 2007; fitzjohn et al., 2009) and were rapidly extended to multistate traits (musse), quantitative traits (quasse, fitzjohn, 2010), incorporating cladogenetic transitions (classe, goldberg & igi\002c, 2012; and bisseness, magnuson-ford & otto, 2012) and other effects (see diversitree website, http://www.zoology.ubc.ca/ prog/diversitree/). other methods designed to detect shifts in speciation and extinction rates (alfaro et al., 2009; stadler, 2011; drummond et al., 2012a) can be used together with trait-based analyses. most of these methods account for incomplete sampling (e.g. fitzjohn

of dioecy and the long-term survival of dioecious species, being a more powerful alternative than the sister clade comparisons we used here. however, a recent investigation by davis et al. (2013) sheds light on the limits of these methods, by showing that the accuracy and precision of parameter estimation of bisse is greatly reduced when one character represents < 10% of the taxa at the tips. the main problem thus seems to be intrinsically related to the rareness of dioecy in angiosperms (~6%). we made similar observations in our attempts to use bisse to study the effect of dioecy in the

the accuracy and precision of parameter estimation of bisse is greatly reduced when one character represents < 10% of the taxa at the tips. the main problem thus seems to be intrinsically related to the rareness of dioecy in angiosperms (~6%). we made similar observations in our attempts to use bisse to study the effect of dioecy in the genus silene (caryophyllaceae), a genus with 700 species of which fewer than 20 are dioecious (fig. s2). sister clade comparisons, while they undeniably lack some of the advantages of these methods that are explicitly phylogeny based, are a more robust alternative. the

### ./test_pdfs//Ogutcen_et_al_2017_Diversification_rates_in_Antirrhineae_Plantaginac.txt
new world species. old world and new world species represent 78% and 22% of our phylogeny respectively. this ratio is comparable to the ratio of the whole tribe (77% old world species, 23% new world species). next, we examined how pollination mode correlates with diversiﬁcation rates in antirrhineae using the “bisse” function (binary state speciation and extinction; maddison et al., 2007) within the r package diversitree (fitzjohn, 2012). we coded bee pollination as 0, and hummingbird pollination as 1. we estimated speciation rates in taxa with both traits (λ0, λ1), extinction rates in taxa with both traits (μ0, μ1), and character

and the new world extinction rates were shown to be zero. dispersals were only observed from the old world to the new world. no signiﬁcant diﬀerence in extinction or dispersal rates between the two regions was observed (fig. 7). in terms of the eﬀects of pollination mode on diversiﬁcation rates, bisse analysis showed that the rates of speciation, extinction, and character shifts were not signiﬁcantly diﬀerent between bee pollinated and hummingbird pollinated lineages in antirrhineae, and that employing diﬀerent settings that incorporated the potential for sampling bias did not have any eﬀect on the results (table 3). 43 perspectives in plant

2.376 0.000 0.000 0.000 0.000 0.221 0.189 0.22 0.000 0.000 0.000 b. d.f. lnlik aic x2 p full no.sab 7 6 78.665 75.267 −143.33 −138.53 6.795 eq.div 5 77.812 −145.62 1.707 0.00914* 0.426 47 perspectives in plant ecology, evolution and systematics 26 (2017) 39–52 e. ogutcen et al. table 3 bisse analysis results. parameter values (a) and anova results (b) were shown for the “realistic” setting. bee pollination was denoted as 0; hummingbird pollination was denoted as 1. λ: speciation rate, μ: extinction rate, q: character state shift rate. the full model was deﬁned as: λ0 ≠ λ1, μ0 ≠ μ1,

### ./test_pdfs//Schnitzler_et_al_2011_Causes_of_plant_diversification_in_the_cape_biodiv.txt
us to assess the robustness of the observed differences. phylogenetic clustering on the other hand would be expected not only for traits with no impact on divergence but also in cases where traits represent a key innovation. therefore, we tested the effect of each trait on diversification rates using the bisse ln likelihood test (maddison et al. 2007) implemented in mesquite (maddison and maddison 2008). the test calculates the likelihood and parameter estimates of a six-parameter model consisting of speciation, extinction, and character shift rates for both states of a binary trait. for the calculations, each trait was scored as a

table 3), pollinator shifts between sister species occur significantly less frequently than based on our randomizations, revealing again a pattern of phylogenetic clustering, with a low frequency of shifts between sister species (moraea 0.25, p < 0.001; podalyrieae 0, p < 0.001; protea 0.231, p < 0.001; table 3). the bisse ln likelihood test yielded no significant differences in speciation or extinction rates for any of the traits analyzed (table s4). as direct comparisons of the proportion of sisterspecies differences (jsis ) between lineages and between downloaded from https://academic.oup.com/sysbio/article-abstract/60/3/343/1666085 by guest on 02 march 2020 to cryptic speciation, we excluded the

### ./test_pdfs//Zenil_Ferguson_et_al_2019_Interaction_among_ploidy_breeding_system_and_line.txt
or ploidy were excluded. the supporting information contains citations for the numerous original data sources. the dryad archive contains the data and tree files used for analyses (doi: 10.5061/dryad.tb7055f). models in order to test our hypotheses about lineage diversification and trait macroevolution, we fit 29 state-dependent speciation and extinction models (bisse, musse, hisse; maddison et al., 2007; fitzjohn, 2012; beaulieu & o’meara, 2016). sse models contain parameters that describe per-lineage rates of speciation and extinction, specific to each character state (denoted k and l, respectively, with subscripts to indicate the state), along with rates of transitions between states (denoted q for

### ./test_pdfs//Bruy_et_al_2018_Evolution_of_plant_architecture_functional_divers.txt
with a permanova (vegan package for r, oksanen et al., 2018). trait based diversification to test whether one of the architectural classes has contributed more than the others to the diversification of new caledonian atractocarpus (by increasing speciation rates and/or decreasing extinction rates), we used the multiple state speciation extinction (musse) framework (fitzjohn et al., 2009) as implemented in the diversitree package for r (fitzjohn, 2012). ancestral character estimation to determine the putative ancestral architectural class of atractocarpus and infer the evolution of architecture in the frontiers in plant science | www.frontiersin.org 5 december 2018 | volume 9 | article 1775

### ./test_pdfs//Couvreur_et_al_2014_Global_diversification_o_f_a_tropical_plant_growth.txt
least seven independent times because of the three climbing species within dypsis and chamaedorea that were not taken into account in the analysis presented here (both genera coded as non-climbing). at least in chamaedorea, the single climbing species (c. elatior) is nested within the genus validating this assumption (cuenca and asmussen-lange, 2007). in addition, these independent evolutions will be valid if our coding assumptions of calamus and frontiers in genetics | evolutionary and population genetics evolution of climbing palms of climbing palms, a shift probability is visible along its root branch in both cases, but it is not signiﬁcant when compared

